# HTTP 代理端口
port: 7890

# SOCKS5 代理端口
socks-port: 7891

# Linux 和 macOS 的 redir 透明代理端口 (重定向 TCP 和 TProxy UDP 流量)
# redir-port: 7892

# Linux 的透明代理端口（适用于 TProxy TCP 和 TProxy UDP 流量)
# tproxy-port: 7893

# 本地 SOCKS5/HTTP(S) 服务验证
# authentication:
#  - "user1:pass1"
#  - "user2:pass2"

# 允许局域网的连接（可用来共享代理）
allow-lan: true
bind-address: "*"
# 此功能仅在 allow-lan 设置为 true 时生效，支持三种参数：
# "*"                           绑定所有的 IP 地址
# 192.168.122.11                绑定一个的 IPv4 地址
# "[aaaa::a8aa:ff:fe09:57d8]"   绑定一个 IPv6 地址

# Clash 路由工作模式
# 规则模式：rule（规则） / global（全局代理）/ direct（全局直连）
mode: rule

# Clash 默认将日志输出至 STDOUT
# 设置日志输出级别 (默认级别：silent，即不输出任何内容，以避免因日志内容过大而导致程序内存溢出）。
# 5 个级别：silent / info / warning / error / debug。级别越高日志输出量越大，越倾向于调试，若需要请自行开启。
log-level: silent

# clash 的 RESTful API 监听地址
external-controller: 127.0.0.1:9090

# 存放配置文件的相对路径，或存放网页静态资源的绝对路径
# Clash core 将会将其部署在 http://{{external-controller}}/ui
# external-ui: folder

# RESTful API 的口令 (可选)
# 通过 HTTP 头中 Authorization: Bearer ${secret} 参数来验证口令
# 当 RESTful API 的监听地址为 0.0.0.0 时，请务必设定口令以保证安全
# secret: ""

# 出站网卡接口
# interface-name: en0

# DNS 服务器和建立连接时的 静态 Hosts, 仅在 dns.enhanced-mode 模式为 redir-host 生效
# 支持通配符域名 (例如: *.clash.dev, *.foo.*.example.com )
# 不使用通配符的域名优先级高于使用通配符的域名 (例如: foo.example.com > *.example.com > .example.com )
# 注意: +.foo.com 的效果等同于 .foo.com 和 foo.com
hosts:
# '*.clash.dev': 127.0.0.1
# '.dev': 127.0.0.1
# 'alpha.clash.dev': '::1'

# DNS 服务器配置(可选；若不配置，程序内置的 DNS 服务会被关闭)
dns:
  enable: true
  listen: 0.0.0.0:53
  ipv6: true # 当此选项为 false 时, AAAA 请求将返回空

  # 以下填写的 DNS 服务器将会被用来解析 DNS 服务的域名
  # 仅填写 DNS 服务器的 IP 地址
  default-nameserver:
    - 223.5.5.5
    - 114.114.114.114
  enhanced-mode: fake-ip # 或 redir-host
  fake-ip-range: 198.18.0.1/16 # Fake IP 地址池 (CIDR 形式)
  # use-hosts: true # 查询 hosts 并返回 IP 记录

  # 在以下列表的域名将不会被解析为 fake ip，这些域名相关的解析请求将会返回它们真实的 IP 地址
  fake-ip-filter:
    # 以下域名列表参考自 vernesong/OpenClash 项目，并由 Hackl0us 整理补充
    # === LAN ===
    - '*.lan'
    # === Linksys Wireless Router ===
    - '*.linksys.com'
    - '*.linksyssmartwifi.com'
    # === Apple Software Update Service ===
    - 'swscan.apple.com'
    - 'mesu.apple.com'
    # === Windows 10 Connnect Detection ===
    - '*.msftconnecttest.com'
    - '*.msftncsi.com'
    # === NTP Service ===
    - 'time.*.com'
    - 'time.*.gov'
    - 'time.*.edu.cn'
    - 'time.*.apple.com'

    - 'time1.*.com'
    - 'time2.*.com'
    - 'time3.*.com'
    - 'time4.*.com'
    - 'time5.*.com'
    - 'time6.*.com'
    - 'time7.*.com'

    - 'ntp.*.com'
    - 'ntp.*.com'
    - 'ntp1.*.com'
    - 'ntp2.*.com'
    - 'ntp3.*.com'
    - 'ntp4.*.com'
    - 'ntp5.*.com'
    - 'ntp6.*.com'
    - 'ntp7.*.com'

    - '*.time.edu.cn'
    - '*.ntp.org.cn'
    - '+.pool.ntp.org'

    - 'time1.cloud.tencent.com'
    # === Music Service ===
    ## NetEase
    - '+.music.163.com'
    - '*.126.net'
    ## Baidu
    - 'musicapi.taihe.com'
    - 'music.taihe.com'
    ## Kugou
    - 'songsearch.kugou.com'
    - 'trackercdn.kugou.com'
    ## Kuwo
    - '*.kuwo.cn'
    ## JOOX
    - 'api-jooxtt.sanook.com'
    - 'api.joox.com'
    - 'joox.com'
    ## QQ
    - '+.y.qq.com'
    - '+.music.tc.qq.com'
    - 'aqqmusic.tc.qq.com'
    - '+.stream.qqmusic.qq.com'
    ## Xiami
    - '*.xiami.com'
    ## Migu
    - '+.music.migu.cn'
    # === Game Service ===
    ## Nintendo Switch
    - '+.srv.nintendo.net'
    ## Sony PlayStation
    - '+.stun.playstation.net'
    ## Microsoft Xbox
    - 'xbox.*.microsoft.com'
    - '+.xboxlive.com'
    # === Other ===
    ## QQ Quick Login
    - 'localhost.ptlogin2.qq.com'
    ## Golang
    - 'proxy.golang.org'
    ## STUN Server
    - 'stun.*.*'
    - 'stun.*.*.*'

  # 支持 UDP / TCP / DoT / DoH 协议的 DNS 服务，可以指明具体的连接端口号。
  # 所有 DNS 请求将会直接发送到服务器，不经过任何代理。
  # Clash 会使用最先获得的解析记录回复 DNS 请求
  nameserver:
    - https://doh.pub/dns-query
    - https://dns.alidns.com/dns-query

  # 当 fallback 参数被配置时, DNS 请求将同时发送至上方 nameserver 列表和下方 fallback 列表中配置的所有 DNS 服务器.
  # 当解析得到的 IP 地址的地理位置不是 CN 时，clash 将会选用 fallback 中 DNS 服务器的解析结果。
  # fallback:
  #   - https://dns.google/dns-query

  # 如果使用 nameserver 列表中的服务器解析的 IP 地址在下方列表中的子网中，则它们被认为是无效的，
  # Clash 会选用 fallback 列表中配置 DNS 服务器解析得到的结果。
  #
  # 当 fallback-filter.geoip 为 true 且 IP 地址的地理位置为 CN 时，
  # Clash 会选用 nameserver 列表中配置 DNS 服务器解析得到的结果。
  #
  # 当 fallback-filter.geoip 为 false, 如果解析结果不在 fallback-filter.ipcidr 范围内，
  # Clash 总会选用 nameserver 列表中配置 DNS 服务器解析得到的结果。
  #
  # 采取以上逻辑进行域名解析是为了对抗 DNS 投毒攻击。
  fallback-filter:
    geoip: false
    ipcidr:
      - 240.0.0.0/4
      - 0.0.0.0/32
    # domain:
    #   - '+.google.com'
    #   - '+.facebook.com'
    #   - '+.youtube.com'

tun:
  enable: false #如果需要启用 TUN 模式，请设置为 true
  stack: system # 或 gvisor
  macOS-auto-route: true
  macOS-auto-detect-interface: true
  dns-hijack:
    - tcp://8.8.8.8:53
    - tcp://8.8.4.4:53

proxies:
  # shadowsocks
  # 支持加密方式：
  #   aes-128-gcm aes-192-gcm aes-256-gcm
  #   aes-128-cfb aes-192-cfb aes-256-cfb
  #   aes-128-ctr aes-192-ctr aes-256-ctr
  #   rc4-md5 chacha20 chacha20-ietf xchacha20
  #   chacha20-ietf-poly1305 xchacha20-ietf-poly1305

  -
    name: '专线 冷门-俄罗斯'
    type: ss
    server: iepl01.node.beer
    port: 9582
    cipher: aes-128-gcm
    password: wDnKZU
    udp: false
    plugin: obfs
    plugin-opts:
      mode: http
      host: f7dcc41733.apple.com
  -
    name: '专线 冷门-印度'
    type: ss
    server: iepl02.node.beer
    port: 9588
    cipher: aes-128-gcm
    password: wDnKZU
    udp: false
    plugin: obfs
    plugin-opts:
      mode: http
      host: f7dcc41733.apple.com
  -
    name: '专线 冷门-土耳其'
    type: ss
    server: iepl03.node.beer
    port: 9585
    cipher: aes-128-gcm
    password: wDnKZU
    udp: false
    plugin: obfs
    plugin-opts:
      mode: http
      host: f7dcc41733.apple.com
  -
    name: '专线 冷门-巴西'
    type: ss
    server: iepl01.node.beer
    port: 9586
    cipher: aes-128-gcm
    password: wDnKZU
    udp: false
    plugin: obfs
    plugin-opts:
      mode: http
      host: f7dcc41733.apple.com
  -
    name: '专线 冷门-德国'
    type: ss
    server: iepl02.node.beer
    port: 9587
    cipher: aes-128-gcm
    password: wDnKZU
    udp: false
    plugin: obfs
    plugin-opts:
      mode: http
      host: f7dcc41733.apple.com
  -
    name: '专线 冷门-澳大利亚'
    type: ss
    server: iepl03.node.beer
    port: 9084
    cipher: aes-128-gcm
    password: wDnKZU
    udp: false
    plugin: obfs
    plugin-opts:
      mode: http
      host: f7dcc41733.apple.com
  -
    name: '专线 冷门-英国'
    type: ss
    server: iepl01.node.beer
    port: 9583
    cipher: aes-128-gcm
    password: wDnKZU
    udp: false
    plugin: obfs
    plugin-opts:
      mode: http
      host: f7dcc41733.apple.com
  -
    name: '专线 冷门-阿根廷'
    type: ss
    server: iepl02.node.beer
    port: 9581
    cipher: aes-128-gcm
    password: wDnKZU
    udp: false
    plugin: obfs
    plugin-opts:
      mode: http
      host: f7dcc41733.apple.com
  -
    name: '专线 台湾 01'
    type: ss
    server: iepl03.node.beer
    port: 9551
    cipher: aes-128-gcm
    password: wDnKZU
    udp: false
    plugin: obfs
    plugin-opts:
      mode: http
      host: f7dcc41733.apple.com
  -
    name: '专线 台湾 02'
    type: ss
    server: iepl01.node.beer
    port: 9552
    cipher: aes-128-gcm
    password: wDnKZU
    udp: false
    plugin: obfs
    plugin-opts:
      mode: http
      host: f7dcc41733.apple.com
  -
    name: '专线 新加坡 01'
    type: ss
    server: iepl02.node.beer
    port: 9541
    cipher: aes-128-gcm
    password: wDnKZU
    udp: false
    plugin: obfs
    plugin-opts:
      mode: http
      host: f7dcc41733.apple.com
  -
    name: '专线 新加坡 02'
    type: ss
    server: iepl03.node.beer
    port: 9542
    cipher: aes-128-gcm
    password: wDnKZU
    udp: false
    plugin: obfs
    plugin-opts:
      mode: http
      host: f7dcc41733.apple.com
  -
    name: '专线 新加坡 03'
    type: ss
    server: iepl01.node.beer
    port: 9543
    cipher: aes-128-gcm
    password: wDnKZU
    udp: false
    plugin: obfs
    plugin-opts:
      mode: http
      host: f7dcc41733.apple.com
  -
    name: '专线 新加坡 04'
    type: ss
    server: iepl02.node.beer
    port: 9544
    cipher: aes-128-gcm
    password: wDnKZU
    udp: false
    plugin: obfs
    plugin-opts:
      mode: http
      host: f7dcc41733.apple.com
  -
    name: '专线 日本 01'
    type: ss
    server: iepl03.node.beer
    port: 9521
    cipher: aes-128-gcm
    password: wDnKZU
    udp: false
    plugin: obfs
    plugin-opts:
      mode: http
      host: f7dcc41733.apple.com
  -
    name: '专线 日本 02'
    type: ss
    server: iepl01.node.beer
    port: 9522
    cipher: aes-128-gcm
    password: wDnKZU
    udp: false
    plugin: obfs
    plugin-opts:
      mode: http
      host: f7dcc41733.apple.com
  -
    name: '专线 日本 03'
    type: ss
    server: iepl02.node.beer
    port: 9523
    cipher: aes-128-gcm
    password: wDnKZU
    udp: false
    plugin: obfs
    plugin-opts:
      mode: http
      host: f7dcc41733.apple.com
  -
    name: '专线 日本 04'
    type: ss
    server: iepl03.node.beer
    port: 9524
    cipher: aes-128-gcm
    password: wDnKZU
    udp: false
    plugin: obfs
    plugin-opts:
      mode: http
      host: f7dcc41733.apple.com
  -
    name: '专线 美国 01'
    type: ss
    server: iepl01.node.beer
    port: 9531
    cipher: aes-128-gcm
    password: wDnKZU
    udp: false
    plugin: obfs
    plugin-opts:
      mode: http
      host: f7dcc41733.apple.com
  -
    name: '专线 美国 02'
    type: ss
    server: iepl02.node.beer
    port: 9532
    cipher: aes-128-gcm
    password: wDnKZU
    udp: false
    plugin: obfs
    plugin-opts:
      mode: http
      host: f7dcc41733.apple.com
  -
    name: '专线 美国 03'
    type: ss
    server: iepl03.node.beer
    port: 9533
    cipher: aes-128-gcm
    password: wDnKZU
    udp: false
    plugin: obfs
    plugin-opts:
      mode: http
      host: f7dcc41733.apple.com
  -
    name: '专线 韩国 01'
    type: ss
    server: iepl01.node.beer
    port: 9561
    cipher: aes-128-gcm
    password: wDnKZU
    udp: false
    plugin: obfs
    plugin-opts:
      mode: http
      host: f7dcc41733.apple.com
  -
    name: '专线 韩国 02'
    type: ss
    server: iepl02.node.beer
    port: 9562
    cipher: aes-128-gcm
    password: wDnKZU
    udp: false
    plugin: obfs
    plugin-opts:
      mode: http
      host: f7dcc41733.apple.com
  -
    name: '专线 香港 01'
    type: ss
    server: iepl03.node.beer
    port: 9511
    cipher: aes-128-gcm
    password: wDnKZU
    udp: false
    plugin: obfs
    plugin-opts:
      mode: http
      host: f7dcc41733.apple.com
  -
    name: '专线 香港 02'
    type: ss
    server: iepl01.node.beer
    port: 9512
    cipher: aes-128-gcm
    password: wDnKZU
    udp: false
    plugin: obfs
    plugin-opts:
      mode: http
      host: f7dcc41733.apple.com
  -
    name: '专线 香港 03'
    type: ss
    server: iepl02.node.beer
    port: 9513
    cipher: aes-128-gcm
    password: wDnKZU
    udp: false
    plugin: obfs
    plugin-opts:
      mode: http
      host: f7dcc41733.apple.com
  -
    name: '专线 马来西亚 01'
    type: ss
    server: iepl02.node.beer
    port: 9571
    cipher: aes-128-gcm
    password: wDnKZU
    udp: false
    plugin: obfs
    plugin-opts:
      mode: http
      host: f7dcc41733.apple.com
  -
    name: '专线 马来西亚 02'
    type: ss
    server: iepl03.node.beer
    port: 9572
    cipher: aes-128-gcm
    password: wDnKZU
    udp: false
    plugin: obfs
    plugin-opts:
      mode: http
      host: f7dcc41733.apple.com
  -
    name: '中继 新加坡 01'
    type: ss
    server: in03.node.beer
    port: 9506
    cipher: aes-128-gcm
    password: wDnKZU
    udp: false
    plugin: obfs
    plugin-opts:
      mode: http
      host: f7dcc41733.apple.com
  -
    name: '中继 新加坡 02'
    type: ss
    server: in02.node.beer
    port: 9507
    cipher: aes-128-gcm
    password: wDnKZU
    udp: false
    plugin: obfs
    plugin-opts:
      mode: http
      host: f7dcc41733.apple.com
  -
    name: '中继 美国 01'
    type: ss
    server: in02.node.beer
    port: 9505
    cipher: aes-128-gcm
    password: wDnKZU
    udp: false
    plugin: obfs
    plugin-opts:
      mode: http
      host: f7dcc41733.apple.com
  -
    name: '中继 香港 01'
    type: ss
    server: in01.node.beer
    port: 9501
    cipher: aes-128-gcm
    password: wDnKZU
    udp: false
    plugin: obfs
    plugin-opts:
      mode: http
      host: f7dcc41733.apple.com
  -
    name: '中继 香港 02'
    type: ss
    server: in02.node.beer
    port: 9502
    cipher: aes-128-gcm
    password: wDnKZU
    udp: false
    plugin: obfs
    plugin-opts:
      mode: http
      host: f7dcc41733.apple.com

proxy-groups:
  # 代理的转发链, 在 proxies 中不应该包含 relay. 不支持 UDP.
  # 流量: clash <-> http <-> vmess <-> ss1 <-> ss2 <-> 互联网
- 
  name: Proxy
  type: select
  proxies:
    - '专线 冷门-俄罗斯'
    - '专线 冷门-印度'
    - '专线 冷门-土耳其'
    - '专线 冷门-巴西'
    - '专线 冷门-德国'
    - '专线 冷门-澳大利亚'
    - '专线 冷门-英国'
    - '专线 冷门-阿根廷'
    - '专线 台湾 01'
    - '专线 台湾 02'
    - '专线 新加坡 01'
    - '专线 新加坡 02'
    - '专线 新加坡 03'
    - '专线 新加坡 04'
    - '专线 日本 01'
    - '专线 日本 02'
    - '专线 日本 03'
    - '专线 日本 04'
    - '专线 美国 01'
    - '专线 美国 02'
    - '专线 美国 03'
    - '专线 韩国 01'
    - '专线 韩国 02'
    - '专线 香港 01'
    - '专线 香港 02'
    - '专线 香港 03'
    - '专线 马来西亚 01'
    - '专线 马来西亚 02'
    - '中继 新加坡 01'
    - '中继 新加坡 02'
    - '中继 美国 01'
    - '中继 香港 01'
    - '中继 香港 02'
-
  name: Domestic
  type: select
  proxies:
    - 'DIRECT'
    - 'Proxy'
-
  name: Others
  type: select
  proxies:
    - 'DIRECT'
    - 'Proxy'

rule-providers:
  apple-proxy:
    type: http
    behavior: classical
    url: "https://cdn.jsdelivr.net/gh/yyl125/PersonalRules@master/Rulesets/Clash/Apple-proxy.yaml"
    path: ./ruleset/Apple-proxy.yaml
    interval: 3600

  apple-direct:
    type: http
    behavior: classical
    url: "https://cdn.jsdelivr.net/gh/yyl125/PersonalRules@master/Rulesets/Clash/Apple-direct.yaml"
    path: ./ruleset/Apple-direct.yaml
    interval: 3600

  cn:
    type: http
    behavior: classical
    url: "https://cdn.jsdelivr.net/gh/yyl125/PersonalRules@master/Rulesets/Clash/CN.yaml"
    path: ./ruleset/CN.yaml
    interval: 3600

  ad-keyword:
    type: http
    behavior: classical
    url: "https://cdn.jsdelivr.net/gh/yyl125/PersonalRules@master/Rulesets/Clash/common-ad-keyword.yaml"
    path: ./ruleset/common-ad-keyword.yaml
    interval: 3600

  foreign:
    type: http
    behavior: classical
    url: "https://cdn.jsdelivr.net/gh/yyl125/PersonalRules@master/Rulesets/Clash/foreign.yaml"
    path: ./ruleset/foreign.yaml
    interval: 3600

  netflix:
    type: http
    behavior: classical
    url: "https://cdn.jsdelivr.net/gh/yyl125/PersonalRules@master/Rulesets/Clash/Netflix.yaml"
    path: ./ruleset/Netflix.yaml
    interval: 3600

  telegram:
    type: http
    behavior: classical
    url: "https://cdn.jsdelivr.net/gh/yyl125/PersonalRules@master/Rulesets/Clash/Telegram.yaml"
    path: ./ruleset/Telegram.yaml
    interval: 3600

  suck:
    type: http
    behavior: classical
    url: "https://cdn.jsdelivr.net/gh/yyl125/PersonalRules@master/Rulesets/Clash/Suck.yaml"
    path: ./ruleset/Suck.yaml
    interval: 3600

  lan:
    type: http
    behavior: classical
    url: "https://cdn.jsdelivr.net/gh/yyl125/PersonalRules@master/Rulesets/Clash/LAN.yaml"
    path: ./ruleset/LAN.yaml
    interval: 3600

rules:
  - RULE-SET,apple-proxy,Proxy
  - RULE-SET,apple-direct,DIRECT
  - RULE-SET,cn,DIRECT
  - RULE-SET,ad-keyword,REJECT
  - RULE-SET,reject,REJECT
  - RULE-SET,foreign,Proxy
  - RULE-SET,telegram,Proxy
  - RULE-SET,lan,DIRECT
  - GEOIP,CN,DIRECT
  - MATCH,Proxy